#!/bin/bash

########
#
# Split tmux window twice, resize, and open vim on the right pane
#

# Original command
# problem is when i close vim the screen closes
#tmux split-window -h -p 65 "vim -c 'NERDTreeToggle|wincmd h'"

# New variation of above command, does not close screen on vim close
tmux split-window -h -p 65 
tmux send-keys -t right "vim -c 'NERDTreeToggle|wincmd h'" Enter

#split right pane horizontally
tmux split-window -t 1 -v

#go back to left pane
tmux select-pane -L